### ISSUE TITLE
RuntimeError: aten::grid_sampler_2d_backward() 

### ISSUE THREAD

**Issue by secretsather** [PDillis/stylegan3-fun#11]
**Running train.py results in the following runtime error:**
RuntimeError: aten::grid_sampler_2d_backward() is missing value for argument 'output_mask'. Declaration: aten::grid_sampler_2d_backward(Tensor grad_output, Tensor input, Tensor grid, int interpolation_mode, int padding_mode, bool align_corners, bool[2] output_mask) -> (Tensor, Tensor)

 - OS: Windows 11
 - PyTorch version 1.11
 - CUDA toolkit version 11.6
 - GPU GTX 3080ti
 - Docker: did you use Docker?  No

**Changes from the below commit to conv2d_gradfix.py & grid_sample_gradfix.py will correct issues:**
 https://github.com/NVlabs/stylegan3/commit/407db86e6fe432540a22515310188288687858fa

**Comment by PDillis** [comment]
Thanks, I have updated the code to work with PyTorch 1.11 in PR #12. Check it in case there's anything wrong.
