### ISSUE TITLE
is it possible to use the stylemix options in the generation code?

### ISSUE THREAD

**Issue by nicolai256** [PDillis/stylegan3-fun#22]
is it possible to activate this in the generate video code?
![image](https://user-images.githubusercontent.com/68881396/185818778-0935896b-8a02-432a-9261-a6ddfdfdd3d3.png)

**Comment by PDillis** [comment]
Yes, this is what [`style_mixing.py`](https://github.com/PDillis/stylegan3-fun/blob/main/style_mixing.py) is for. An explanation of the code can be found [here](https://github.com/PDillis/stylegan2-fun#style), but note that StyleGAN3 models no longer have the fine, middle, and coarse layers as in StyleGAN2, as well as having 14 layers irrespective of the image resolution.
